SET COMPILER="path\to\AtlusScriptCompiler.exe"
SET OUTPUT_PATH=path\to\Aemulus Package Manager\Packages\Persona 3 FES\P3 Fes Mod Menu

IF NOT EXIST "%OUTPUT_PATH%" MKDIR "%OUTPUT_PATH%"
IF NOT EXIST "%OUTPUT_PATH%\DATA\FIELD\PACK\F008_003" MKDIR "%OUTPUT_PATH%\DATA\FIELD\PACK\F008_003"
IF NOT EXIST "%OUTPUT_PATH%\DATA\FIELD\SCRIPT" MKDIR "%OUTPUT_PATH%\DATA\FIELD\SCRIPT"

%COMPILER% DATA\FIELD\SCRIPT\FIELD.BF.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\DATA\FIELD\SCRIPT\FIELD.BF" -Hook

%COMPILER% DATA\FIELD\PACK\f008.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\DATA\FIELD\PACK\F008_003\f008.bf" -Hook