SET COMPILER="path\to\AtlusScriptCompiler\Tool\AtlusScriptCompiler.exe"
SET OUTPUT_PATH=path\to\Mod Compendium\Mods\Persona3\Persona 3 FES Mod Menu
SET PAKPACK="path\to\PAKPack\PAKPack.exe"

IF NOT EXIST "%OUTPUT_PATH%" MKDIR "%OUTPUT_PATH%"
IF NOT EXIST "%OUTPUT_PATH%\Data" MKDIR "%OUTPUT_PATH%\Data"
IF NOT EXIST "%OUTPUT_PATH%\Data\DATA\FIELD\PACK" MKDIR "%OUTPUT_PATH%\Data\DATA\FIELD\PACK"
IF NOT EXIST "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT" MKDIR "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT"

%COMPILER% DATA\FIELD\SCRIPT\NPCCOMU.BF.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT\NPCCOMU.BF" -Hook
%COMPILER% DATA\FIELD\SCRIPT\FIELD.BF.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT\FIELD.BF" -Hook

%COMPILER% DATA\FIELD\PACK\f008.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out build\DATA\FIELD\PACK\F008_003\f008.bf -Hook

%PAKPACK% replace DATA\FIELD\PACK\F008_003.PAC f008.bf build\DATA\FIELD\PACK\F008_003\f008.BF "%OUTPUT_PATH%\Data\DATA\FIELD\PACK\F008_003.PAC"

rd /s /q build