SET COMPILER="D:\@Persona Modding tools\AtlusScriptCompiler\Tool\AtlusScriptCompiler.exe"
SET OUTPUT_PATH=D:\@Persona Modding tools\Mod Compendium\Mods\Persona3\Persona 3 FES Mod Menu
SET PAKPACK="D:\@Persona Modding tools\PAKPack\PAKPack.exe"

IF NOT EXIST "%OUTPUT_PATH%" MKDIR "%OUTPUT_PATH%"
IF NOT EXIST "%OUTPUT_PATH%\Data" MKDIR "%OUTPUT_PATH%\Data"
IF NOT EXIST "%OUTPUT_PATH%\Data\DATA\FIELD\PACK" MKDIR "%OUTPUT_PATH%\Data\DATA\FIELD\PACK"
IF NOT EXIST "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT" MKDIR "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT"

%COMPILER% DATA\FIELD\SCRIPT\NPCCOMU.BF.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT\NPCCOMU.BF" -Hook
%COMPILER% DATA\FIELD\SCRIPT\FIELD.BF.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out "%OUTPUT_PATH%\Data\DATA\FIELD\SCRIPT\FIELD.BF" -Hook

%COMPILER% DATA\FIELD\PACK\f004.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out build\DATA\FIELD\PACK\F004_010\f004.BF -Hook
%COMPILER% DATA\FIELD\PACK\f007.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out build\DATA\FIELD\PACK\F007_002\f007.BF -Hook
%COMPILER% DATA\FIELD\PACK\f008.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out build\DATA\FIELD\PACK\F008_003\f008.BF -Hook
%COMPILER% DATA\FIELD\PACK\f032.bf.flow -Compile -OutFormat V1 -Library P3F -Encoding P3 -Out build\DATA\FIELD\PACK\F032_002\f032.BF -Hook

%PAKPACK% replace DATA\FIELD\PACK\F004_010.PAC f004.BF build\DATA\FIELD\PACK\F004_010\f004.BF "%OUTPUT_PATH%\Data\DATA\FIELD\PACK\F004_010.PAC"
%PAKPACK% replace DATA\FIELD\PACK\F007_002.PAC f007.BF build\DATA\FIELD\PACK\F007_002\f007.BF "%OUTPUT_PATH%\Data\DATA\FIELD\PACK\F007_002.PAC"
%PAKPACK% replace DATA\FIELD\PACK\F008_003.PAC f008.BF build\DATA\FIELD\PACK\F008_003\f008.BF "%OUTPUT_PATH%\Data\DATA\FIELD\PACK\F008_003.PAC"
%PAKPACK% replace DATA\FIELD\PACK\F032_002.PAC f032.BF build\DATA\FIELD\PACK\F032_002\f032.BF "%OUTPUT_PATH%\Data\DATA\FIELD\PACK\F032_002.PAC"

rd /s /q build