[sel Mod_Menu]
[f 0 8 -258][f 1 31]Call Menu[e]
[f 0 8 -258][f 1 31]                    Flag Menu[e]
[f 0 8 -258][f 1 31]Facilities[e]
[f 0 8 -258][f 1 31]                    Misc.[e]
[f 0 8 -258][f 1 31]Fast Travel[e]
[f 0 8 -258][f 1 31]                    Save[e]

[sel Misc_Menu]
[f 0 8 -258][f 1 31]Set Yen[e]
[f 0 8 -258][f 1 31]                    Set Item[e]
[f 0 8 -258][f 1 31]Max S. Stats[e]
[f 0 8 -258][f 1 31]                    Max P. Stats[e]
[f 0 8 -258][f 1 31]Change Date[e]
[f 0 8 -258][f 1 31]                    Add Member[e]
[f 0 8 -258][f 1 31]Remove Member[e]
[f 0 8 -258][f 1 31]                    Font Test[e]

[sel Item_Group]
[f 0 8 -258][f 1 31]Weapon[e]
[f 0 8 -258][f 1 31]                    Armor/Outfit[e]
[f 0 8 -258][f 1 31]Boots[e]
[f 0 8 -258][f 1 31]                    Accessory[e]
[f 0 8 -258][f 1 31]Item[e]
[f 0 8 -258][f 1 31]                    Key Item[e]

[msg Select_Item_Group]
[f 0 8 -258][f 1 31]Which item group?[n][e]

[msg Select_Weapon]
[f 0 8 -258][f 1 31]Weapon I.D. (3 digits)[n][e]

[msg Select_ArmorOutfit]
[f 0 8 -258][f 1 31]Armor/Outfit I.D. (3 digits)[n][e]

[msg Select_Boots]
[f 0 8 -258][f 1 31]Boots I.D. (3 digits)[n][e]

[msg Select_Accessory]
[f 0 8 -258][f 1 31]Accessory I.D. (3 digits)[n][e]

[msg Select_Item]
[f 0 8 -258][f 1 31]Item I.D. (3 digits)[n][e]

[msg Select_KeyItem]
[f 0 8 -258][f 1 31]Key Item I.D. (3 digits)[n][e]

[msg Confirm_Item]
[f 0 8 -258][f 1 31]Item selected:[n][f 0 25 0] × [f 0 3 1][e]

[msg SetAmount]
[f 0 8 -258][f 1 31]How much? (2 digits)[e]

[sel Facilities_Menu]
[f 0 8 -258][f 1 31]Velvet Room[e]
[f 0 8 -258][f 1 31]Police Station[e]
[f 0 8 -258][f 1 31]Aohige Pharmacy[e]
[f 0 8 -258][f 1 31]Shinshoudo Antiques[e]
[f 0 8 -258][f 1 31]Be Blue V[e]

[sel Call_Menu]
[f 0 8 -258][f 1 31]Call Event[e]
[f 0 8 -258][f 1 31]                    Call Field[e]
[f 0 8 -258][f 1 31]Call Battle[e]
[f 0 8 -258][f 1 31]                    Call BGM[e]
[f 0 8 -258][f 1 31]Call Movie[e]
[f 0 8 -258][f 1 31]                    Call Floor[e]

[sel Flag_Menu]
[f 0 8 -258][f 1 31]Enable All Flags[e]
[f 0 8 -258][f 1 31]Disable All Flags[e]
[f 0 8 -258][f 1 31]Print Enabled Flags[e]
[f 0 8 -258][f 1 31]Manual Input[e]
[f 0 8 -258][f 1 31]Select Range[e]

[sel Num_Menu]
[f 0 5 -258][f 1 31] 0[e]
[f 0 5 -258][f 1 31]     1[e]
[f 0 5 -258][f 1 31]         2[e]
[f 0 5 -258][f 1 31]             3[e]
[f 0 5 -258][f 1 31]                 4[e]
[f 0 5 -258][f 1 31]                     5[e]
[f 0 5 -258][f 1 31]                         6[e]
[f 0 5 -258][f 1 31]                             7[e]
[f 0 5 -258][f 1 31]                                 8[e]
[f 0 5 -258][f 1 31]                                     9[e]

[msg Mod]
[f 0 8 -258][f 1 31]Mod Menu[n][e]

[msg Misc]
[f 0 8 -258][f 1 31]Misc. Menu[n][e]

[msg Call]
[f 0 8 -258][f 1 31]Call Menu[n][e]

[msg Flag]
[f 0 8 -258][f 1 31]Flag Menu[n][e]

[msg Facilities]
[f 0 8 -258][f 1 31]Facilities[n][e]

[msg SelectMajor]
[f 0 8 -258][f 1 31]Major I.D. (3 digits)[n][e]

[msg SelectMinor]
[f 0 8 -258][f 1 31]Minor I.D. (3 digits)[n][e]

[msg SelectYen]
[f 0 8 -258][f 1 31]Yen (7 digits)[n][e]

[msg SelectID1]
[f 0 8 -258][f 1 31]I.D. (1 digit)[n][e]

[msg SelectID2]
[f 0 8 -258][f 1 31]I.D. (2 digits)[n][e]

[msg SelectID3]
[f 0 8 -258][f 1 31]I.D. (3 digits)[n][e]

[msg SelectFlag]
[f 0 8 -258][f 1 31]Flag (4 digits)[n][e]

[msg SelectLowerFlag]
[f 0 8 -258][f 1 31]Lower Index of Flags (4 digits)[n][e]

[msg SelectUpperFlag]
[f 0 8 -258][f 1 31]Upper Index of Flags (4 digits)[n][e]

[msg SelectPosition]
[f 0 8 -258][f 1 31]Entry point I.D. (2 digits)[n][e]

[msg SelectFloor]
[f 0 8 -258][f 1 31]Which floor? (3 digits)[n][e]

[msg Month]
[f 0 8 -258][f 1 31]Month (2 digits)[n][e]

[msg Day]
[f 0 8 -258][f 1 31]Day (2 digits)[n][e]

[msg Time]
[f 0 8 -258][f 1 31]Time (1 digit)[n][e]

[msg Confirmation]
[f 0 8 -258][f 1 31]Confirm [f 0 3 0]?[n][e]

[sel YesNo]
[f 0 5 -258][f 1 31]Yes[e]
[f 0 5 -258][f 1 31]No[e]

[sel OnOff]
[f 0 5 -258][f 1 31]On[e]
[f 0 5 -258][f 1 31]Off[e]
[f 0 5 -258][f 1 31]Cancel[e]

[msg CurrentFlag]
[f 0 8 -258][f 1 31]Flag [f 0 3 0] is currently set to [f 0 3 1][n][e]

[msg FlagRange]
[f 0 8 -258][f 1 31]Turn range of flags on or off?[n][e]

[msg FlagError]
[f 0 8 -258][f 1 31]Please choose an upper index greater[n]than lower index.[n][f 0 4][e]

[msg FlagConfirmation]
[f 0 8 -258][f 1 31]Flag [f 0 3 0] set to [f 0 3 1][n][e]

[msg FontTest [Font Testing]]
[f 0 8 -258][f 1 31]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n]1234567890-_.:,;|!"#$%&/()=?+*{}^\<>`~'@[n][f 0 4][e]
