[sel Mod_Menu]
[f 0 8 -258][f 1 31]Call Event[e]
[f 0 8 -258][f 1 31]                    Call Field[e]
[f 0 8 -258][f 1 31]Call Battle[e]
[f 0 8 -258][f 1 31]                    Call BGM[e]
[f 0 8 -258][f 1 31]Call Movie[e]
[f 0 8 -258][f 1 31]                    Call Floor[e]
[f 0 8 -258][f 1 31]Change Flag[e]
[f 0 8 -258][f 1 31]                    Facilities[e]
[f 0 8 -258][f 1 31]Fast Travel[e]
[f 0 8 -258][f 1 31]                    Save[e]

[sel Facilities_Menu]
[f 0 8 -258][f 1 31]Velvet Room[e]
[f 0 8 -258][f 1 31]                     Police Station[e]
[f 0 8 -258][f 1 31]Aohige Pharmacy[e]
[f 0 8 -258][f 1 31]              Shinshoudo Antiques[e]
[f 0 8 -258][f 1 31]Be Blue V[e]

[sel Num_Menu]
[f 0 5 -258][f 1 31] 0[e]
[f 0 5 -258][f 1 31]     1[e]
[f 0 5 -258][f 1 31]         2[e]
[f 0 5 -258][f 1 31]             3[e]
[f 0 5 -258][f 1 31]                 4[e]
[f 0 5 -258][f 1 31]                     5[e]
[f 0 5 -258][f 1 31]                         6[e]
[f 0 5 -258][f 1 31]                             7[e]
[f 0 5 -258][f 1 31]                                 8[e]
[f 0 5 -258][f 1 31]                                     9[e]

[msg Welcome]
[f 0 8 -258][f 1 31]Mod Menu[n][f 0 4][e]

[msg SelectMajor]
[f 0 8 -258][f 1 31]Major I.D. (3 digits)[n][f 0 4][e]

[msg SelectMinor]
[f 0 8 -258][f 1 31]Minor I.D. (3 digits)[n][f 0 4][e]

[msg SelectID2]
[f 0 8 -258][f 1 31]I.D. (2 digits)[n][f 0 4][e]

[msg SelectID3]
[f 0 8 -258][f 1 31]I.D. (3 digits)[n][f 0 4][e]

[msg SelectFlag]
[f 0 8 -258][f 1 31]Flag (4 digits)[n][f 0 4][e]

[msg SelectPosition]
[f 0 8 -258][f 1 31]Entry point I.D. (2 digits)[n][f 0 4][e]

[msg SelectFloor]
[f 0 8 -258][f 1 31]Which floor? (3 digits)[n][f 0 4][e]

[msg Confirmation]
[f 0 8 -258][f 1 31]Confirm [f 0 3 0]?[n][f 0 4][e]

[sel YesNo]
[f 0 5 -258][f 1 31]Yes[e]
[f 0 5 -258][f 1 31]No[e]

[sel OnOff]
[f 0 5 -258][f 1 31]On[e]
[f 0 5 -258][f 1 31]Off[e]
[f 0 5 -258][f 1 31]Cancel[e]

[msg CurrentFlag]
[f 0 8 -258][f 1 31]Flag [f 0 3 0] is currently set to [f 0 3 1][n][f 0 4][e]

[msg FlagConfirmation]
[f 0 8 -258][f 1 31]Flag [f 0 3 0] set to [f 0 3 1][n][f 0 4][e]